#!/bin/bash
SQUEEZEPLAY=squeezeplay
TOPDIR=`pwd`
BUILDDIR=${TOPDIR}/sp-build
OUTPUT=${BUILDDIR}/opt/${SQUEEZEPLAY}
TCZ=${TOPDIR}/pcp-${SQUEEZEPLAY}.tcz
TCZINFO=${TCZ}.info

if [ -d $BUILDDIR ]; then
	rm -rf $BUILDDIR
fi

mkdir -p $OUTPUT || exit 1

tar -x -C $OUTPUT -f ${TOPDIR}/squeezeplay-7.8.0.tgz

cp -pr $HOME/source/picoreplayer/tcz/jivelite/DisplayOff $OUTPUT/share/jive/applets/
cp -pr $HOME/source/picoreplayer/tcz/jivelite/piCorePlayer $OUTPUT/share/jive/applets/

cd $OUTPUT/share/jive/applets/piCorePlayer
patch -p0 -i$OUTPUT/../../../squeezeplay-picoreplayermeta.patch || exit 1
patch -p0 -i$OUTPUT/../../../squeezeplay-picoreplayerapplet.patch || exit 1

cd $OUTPUT || exit 1

patch -p0 -i$OUTPUT/../../../squeezeplay-removeappletinstallerreboot.patch || exit 1
patch -p0 -i$OUTPUT/../../../squeezeplay-defaultjogglerskin.patch || exit 1

rm share/jive/applets/JogglerSkin/images/UNOFFICIAL/VUMeter/{vu_analog_25seq_b.png,vu_analog_25seq_w.png} || exit 1
rm -rf share/jive/applets/BlankScreen || exit 1
cp -p $HOME/source/picoreplayer/tcz/jivelite/vu_analog_25seq_k.png share/jive/applets/JogglerSkin/images/UNOFFICIAL/VUMeter/vu_analog_25seq_w.png || exit 1
cp -p $HOME/source/picoreplayer/tcz/jivelite/pcp.png $OUTPUT/share/jive/jive/splash.png || exit 1

# cp -p $OUTPUT/../../../NewFont.ttf share/jive/fonts/FreeSans.ttf
# cp -p $OUTPUT/../../../NewBoldFont.ttf share/jive/fonts/FreeSansBold.ttf

rm -f bin/{cjpeg,djpeg,freetype-config,jpegtran,libpng12-config,libpng-config,lprof,lua,luac,rdjpgcom,sdl-config,ts_*,wrjpgcom,xmlwf,squeezeplay.sh}
rm -rf etc
rm -rf include
rm -rf man
rm -rf share/{aclocal,doc,man}
rm -rf lib/{pkgconfig,ts}
find lib -type f -name '*\.a' -exec rm {} \;
find lib -type f -name '*\.la' -exec rm {} \;
rm -f lib/libpng.la
rm -f lib/libts*

find lib -type f -name '*so*' -exec patchelf --set-rpath "/opt/squeezeplay/lib" {} \;
patchelf --set-rpath "/opt/squeezeplay/lib:/usr/local/lib" lib/libSDL-1.2.so.0.11.4
patchelf --set-rpath "/opt/squeezeplay/lib:/usr/local/lib" lib/libSDL_gfx.so.13.9.1
find bin -type f -exec patchelf --set-rpath "/opt/squeezeplay/lib" {} \;
find bin -type f -exec strip --strip-unneeded {} \;
cp -p $TOPDIR/${SQUEEZEPLAY}.sh bin/

cd $TOPDIR

if [ -f $TCZ ]; then
        rm $TCZ
fi

mksquashfs sp-build $TCZ -all-root -no-progress
md5sum `basename $TCZ` > ${TCZ}.md5.txt

echo -e "Title:\t\tpcp-$SQUEEZEPLAY.tcz" > $TCZINFO
echo -e "Description:\tCommunity squeezebox controller and player." >> $TCZINFO
echo -e "Version:\t$(strings $OUTPUT/bin/jive | grep 7\.8\.0)" >> $TCZINFO
echo -e "Authors:\tSee About in advanced settings, Ralph Irving, Michael Herger" >> $TCZINFO
echo -e "Original-site:\thttps://github.com/ralph-irving/squeezeplay.git" >> $TCZINFO
echo -e "Copying-policy:\tBSD" >> $TCZINFO
echo -e "Size:\t\t$(ls -lk pcp-$SQUEEZEPLAY.tcz | awk '{print $5}')k" >> $TCZINFO
echo -e "Extension_by:\tpiCorePlayer team: https://sites.google.com/site/picoreplayer" >> $TCZINFO
echo -e "\t\tCompiled for piCore 8.x" >> $TCZINFO
